__add__  # operador +
__sub__  # operador -
__mul__  # operador *
__truediv__  # operador /
__floordiv__  # operador //
__mod__  # operador %
__pow__  # operador **
__and__  # operador &
__xor__  # operador ^
__or__  # operador |