name: PDF

on:
  push:
    branches:
      - 'ci'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full
          sudo apt-get install python3-pygments
          
      - name: Compilar PDF
        run: |
          latexmk -pdf --shell-escape main.tex
          
      #- name: Borrar último lanzamiento
      #  uses: jagger27/delete-release@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: latest

      - name: Añadir etiqueta a la última versión
        run: |
          git checkout ci
          git tag latest -f
          git push --tags -f "https://VictorMardones:$GITHUB_TOKEN@https://github.com/VictorMardones/Resumen-Python-3.git"
          
      - name: Crear nuevo lanzamiento
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
        
      - name: Subir el último PDF
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./Resumen-Python-3/build/main.pdf"
          asset_name: "Resumen Python 3.pdf"
          asset_content_type: application/pdf
